logger:
  file:
    path: /usr/local/var/log/open5gs/bsf.log
  level: info

global:
  max:
    ue: 1024

bsf:
  sbi:
    server:
    - dev: eth0
      port: 7777
    client:
      nrf:
      - uri: http://10.10.0.10:7777
